---
name: Bug Report
description: Create a report to help us improve.
labels: [bug]
assignees: wineee
body:
- type: markdown
  attributes:
    value: |
      **Thanks for taking a minute to file a bug report!**

      ⚠
      Verify first that your issue is not [already reported on
      GitHub][issue search].

      _Please fill out the form below with as many precise
      details as possible._

      [issue search]: ../search?q=is%3Aissue&type=issues

- type: textarea
  attributes:
    label: Describe the bug
    description: >-
      A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: Metadata
    description: >-
      Get nix info to help with debugging.
    placeholder: >-
      Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.
  validations:
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    description: >-
      Describe the steps to reproduce this bug.
    placeholder: |
      1. build *X*

- type: textarea
  attributes:
    label: Logs
    description: |
      log here if short otherwise a link to a gist.

- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context about the problem here.

...
